version: "2.2"
services:
  zidni01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: zidni01
    environment:
      - node.name=zidni01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=zidni02,zidni03
      - cluster.initial_master_nodes=zidni01,zidni02,zidni03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - elastic
  zidni02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: zidni02
    environment:
      - node.name=zidni02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=zidni01,zidni03
      - cluster.initial_master_nodes=zidni01,zidni02,zidni03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - elastic
  zidni03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: zidni03
    environment:
      - node.name=zidni03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=zidni01,zidni02
      - cluster.initial_master_nodes=zidni01,zidni02,zidni03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
